services:
  db:
    image: postgres:15
    container_name: pastelaria-db
    environment:
      POSTGRES_DB: pastelaria
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pastelaria@123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pastelaria"]
      interval: 5s
      retries: 5
      timeout: 3s
      
  api:
    build: .
    ports: 
      - "8181:8181"
    container_name: pastelaria-api
    working_dir: /app/pastelaria-api
    volumes:
      - .:/app/pastelaria-api
    depends_on: 
      db:
        condition: service_healthy
    command: >
      sh -c "php artisan migrate --force && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8181"